services:
  app:
    build: .
    ports:
      - "3001:3001"
    environment:
      DB_PATH: /data/psuparlay.db
      PORT: 3001
      JWT_SECRET: "dev-secret-not-for-prod"
      VAPID_PUBLIC_KEY: "BN8TOqqcECo5I94S9lscOvOqgWzcEIgT3J_gKKieBOYTEzC6U_z2sIq1TVLwabjvQRpvbrt0I7fJ8KJFAhU37yA"
      VAPID_PRIVATE_KEY: "eCtc8TgphgulDTS4V97zrl3DzjJvua8YeuKTe2CEAQk"
    volumes:
      - sqlite_data:/data

volumes:
  sqlite_data:
