apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "psu-parlay.app.fullname" . }}-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "psu-parlay.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.app.storage | quote }}
  {{- with .Values.app.storageClassName }}
  storageClassName: {{ . | quote }}
  {{- end }}
