apiVersion: v1
kind: Service
metadata:
  name: {{ include "psu-parlay.app.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "psu-parlay.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "psu-parlay.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  type: {{ .Values.app.service.type }}
  ports:
    - port: 3001
      targetPort: 3001
      {{- if and (eq .Values.app.service.type "NodePort") .Values.app.service.nodePort }}
      nodePort: {{ .Values.app.service.nodePort }}
      {{- end }}
