{{- if or (not .Values.backend.config.vapidExistingSecret) (not .Values.backend.config.oddsApiExistingSecret) (not .Values.secrets.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "psu-parlay.backend.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "psu-parlay.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
type: Opaque
stringData:
  {{- if not .Values.secrets.existingSecret }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  {{- end }}
  {{- if not .Values.backend.config.vapidExistingSecret }}
  VAPID_PUBLIC_KEY: {{ .Values.backend.config.vapidPublicKey | quote }}
  VAPID_PRIVATE_KEY: {{ .Values.backend.config.vapidPrivateKey | quote }}
  {{- end }}
  {{- if not .Values.backend.config.oddsApiExistingSecret }}
  ODDS_API_KEY: {{ .Values.backend.config.oddsApiKey | quote }}
  {{- end }}
{{- end }}
