apiVersion: v1
kind: Service
metadata:
  name: {{ include "psu-parlay.backend.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "psu-parlay.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  selector:
    app.kubernetes.io/name: {{ include "psu-parlay.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: backend
  ports:
    - port: 3001
      targetPort: 3001
