{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "psu-parlay.postgres.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "psu-parlay.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  selector:
    app.kubernetes.io/name: {{ include "psu-parlay.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: postgres
  ports:
    - port: 5432
      targetPort: 5432
{{- end }}
